import { NextRequest, NextResponse } from "next/server";
import Stripe from "stripe";
import { supabaseAdmin } from "@/lib/supabase";

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: "2024-11-20.acacia",
});

/**
 * POST /api/checkout
 * Creates a Stripe checkout session for purchasing a cover letter
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { applicationId, userEmail } = body;

    if (!applicationId) {
      return NextResponse.json(
        { error: "Application ID is required" },
        { status: 400 }
      );
    }

    // Verify the application exists and isn't already paid
    const { data: application, error: appError } = await supabaseAdmin
      .from("job_applications")
      .select("*")
      .eq("id", applicationId)
      .single();

    if (appError || !application) {
      return NextResponse.json(
        { error: "Application not found" },
        { status: 404 }
      );
    }

    if (application.is_paid) {
      return NextResponse.json(
        { error: "This application has already been paid for" },
        { status: 400 }
      );
    }

    // Get origin for redirect URLs
    const origin = request.headers.get("origin") || 
                   process.env.NEXT_PUBLIC_APP_URL || 
                   "http://localhost:3000";

    // Create Stripe checkout session
    const session = await stripe.checkout.sessions.create({
      mode: "payment",
      payment_method_types: ["card"],
      line_items: [
        {
          price_data: {
            currency: "usd",
            product_data: {
              name: "AI-Powered Cover Letter",
              description: "Professional, ATS-optimized cover letter generated by Gemini AI",
            },
            unit_amount: 300, // $3.00
          },
          quantity: 1,
        },
      ],
      success_url: `${origin}/success?session_id={CHECKOUT_SESSION_ID}&applicationId=${applicationId}`,
      cancel_url: `${origin}/generate?cancelled=true`,
      customer_email: userEmail,
      metadata: {
        applicationId: application.id,
        product: "cover_letter",
      },
      billing_address_collection: "auto",
      expires_at: Math.floor(Date.now() / 1000) + 30 * 60, // 30 minutes
    });

    // Save the Stripe session ID to the application
    await supabaseAdmin
      .from("job_applications")
      .update({ stripe_session_id: session.id })
      .eq("id", applicationId);

    // Create payment record
    await supabaseAdmin
      .from("payments")
      .insert({
        application_id: applicationId,
        stripe_session_id: session.id,
        amount: 300,
        currency: "usd",
        status: "pending",
        customer_email: userEmail,
      });

    return NextResponse.json({
      success: true,
      sessionId: session.id,
      url: session.url,
    });

  } catch (error: any) {
    console.error("Checkout error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to create checkout session" },
      { status: 500 }
    );
  }
}