import { NextRequest, NextResponse } from "next/server";
import Stripe from "stripe";
import { createClient } from "@supabase/supabase-js";

// Initialize Supabase Admin with Service Role Key
const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// Updated to match the 2026 Clover SDK version
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: "2026-01-28.clover",
});

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { applicationId } = body;

    console.log("📦 Checkout request for application:", applicationId);

    if (!applicationId) {
      return NextResponse.json({ error: "Application ID is required" }, { status: 400 });
    }

    // 1. Verify the application exists
    const { data: application, error: appError } = await supabaseAdmin
      .from("job_applications")
      .select("*")
      .eq("id", applicationId)
      .single();

    if (appError || !application) {
      return NextResponse.json({ error: "Application not found" }, { status: 404 });
    }

    if (application.is_paid) {
      return NextResponse.json({ error: "Already paid for" }, { status: 400 });
    }

    const origin = request.headers.get("origin") || "http://localhost:3000";

    // 2. Create Stripe checkout session
    const session = await stripe.checkout.sessions.create({
      mode: "payment",
      payment_method_types: ["card"],
      // Use the email from the application if it exists to pre-fill Stripe
      customer_email: application.user_email || undefined,
      line_items: [
        {
          price_data: {
            currency: "usd",
            product_data: {
              name: "AI-Powered Cover Letter",
              description: "Professional, ATS-optimized cover letter generated by Gemini AI",
            },
            unit_amount: 300, // $3.00
          },
          quantity: 1,
        },
      ],
      success_url: `${origin}/success?session_id={CHECKOUT_SESSION_ID}&applicationId=${applicationId}`,
      cancel_url: `${origin}/generate?cancelled=true`,
      metadata: {
        applicationId: application.id,
      },
    });

    console.log("✅ Stripe session created:", session.id);

    // 3. Update the application with the session ID
    await supabaseAdmin
      .from("job_applications")
      .update({
        stripe_session_id: session.id,
        updated_at: new Date().toISOString(),
      })
      .eq("id", applicationId);

    // 4. Create payment record (linking to your Section 8 table)
    await supabaseAdmin
      .from("payments")
      .insert({
        application_id: applicationId,
        stripe_session_id: session.id,
        amount: 300,
        currency: "usd",
        status: "pending",
        customer_email: application.user_email || null, // Tracking email here too
        created_at: new Date().toISOString(),
      });

    return NextResponse.json({
      success: true,
      url: session.url, // This is the link the frontend redirects to
    });

  } catch (error: any) {
    console.error("❌ Checkout error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to create checkout session" },
      { status: 500 }
    );
  }
}