import { NextRequest, NextResponse } from "next/server";
import Stripe from "stripe";
import { createClient } from "@supabase/supabase-js";

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: "2024-11-20.acacia",
});

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { applicationId } = body;

    console.log("📦 Checkout request for application:", applicationId);

    if (!applicationId) {
      return NextResponse.json(
        { error: "Application ID is required" },
        { status: 400 }
      );
    }

    // Verify the application exists
    const { data: application, error: appError } = await supabaseAdmin
      .from("job_applications")
      .select("*")
      .eq("id", applicationId)
      .single();

    if (appError || !application) {
      console.error("Application not found:", appError);
      return NextResponse.json(
        { error: "Application not found" },
        { status: 404 }
      );
    }

    if (application.is_paid) {
      return NextResponse.json(
        { error: "This application has already been paid for" },
        { status: 400 }
      );
    }

    const origin = request.headers.get("origin") || "http://localhost:3000";

    // Create Stripe checkout session
    const session = await stripe.checkout.sessions.create({
      mode: "payment",
      payment_method_types: ["card"],
      line_items: [
        {
          price_data: {
            currency: "usd",
            product_data: {
              name: "AI-Powered Cover Letter",
              description: "Professional, ATS-optimized cover letter generated by Gemini AI",
            },
            unit_amount: 300, // $3.00
          },
          quantity: 1,
        },
      ],
      success_url: `${origin}/success?session_id={CHECKOUT_SESSION_ID}&applicationId=${applicationId}`,
      cancel_url: `${origin}/generate?cancelled=true`,
      metadata: {
        applicationId: application.id,
      },
    });

    console.log("✅ Stripe session created:", session.id);

    // Save session ID
    await supabaseAdmin
      .from("job_applications")
      .update({
        stripe_session_id: session.id,
        updated_at: new Date().toISOString(),
      })
      .eq("id", applicationId);

    // Create payment record
    await supabaseAdmin
      .from("payments")
      .insert({
        application_id: applicationId,
        stripe_session_id: session.id,
        amount: 300,
        currency: "usd",
        status: "pending",
        created_at: new Date().toISOString(),
      });

    return NextResponse.json({
      success: true,
      url: session.url,
    });

  } catch (error: any) {
    console.error("❌ Checkout error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to create checkout session" },
      { status: 500 }
    );
  }
}